server:
  port:
    80

spring:
  datasource:
    url: jdbc:mysql://121.196.146.222:3306/study?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
#    hikari:
#      auto-commit: true
#      connection-test-query: SELECT 1
#      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒 -->
#      connection-timeout: 30000
#      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟 -->
#      idle-timeout: 600000
#      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，
#      #建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
#      max-lifetime: 620000
#      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count) -->
#      maximum-pool-size: 30
#      #池中维护的最小空闲连接数
#      minimum-idle: 5
#      pool-name: DatebookHikariCP
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 121.196.146.222
    password: dyb970324
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 3
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 3
    database: 0
    timeout: 3600

mybatis:
  mapper-locations: classpath:dao/*.xml

jwt:
  tokenHeader: Authorization
  secret: secret
  expiration: 3600         #秒
  tokenHead: 'Bearer '

secure:
  ignored:
    urls: #安全路径白名单
      - /login
      - /register
      - /doc.html
      - /swagger-resources/**
      - /api-docs
      - /swagger-ui.html
      - /v3/api-docs/**
      - /v3/api-docs-ext/**
      - /webjars/**
      - /druid/**
      - /sendMessage

knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: admin
    password: 123456

aliyun:
  accessKeyID: LTAIa0Ri6ELjRxGA
  accessKeySecret: yVzaJoQFBlT4URSnjbDpy8a51t4UpQ
  signName: 成都东软学院在线考试系统
  templateCode: SMS_189245775

sendSms:
  codeExpiration: 300
